import React, { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
// import Image from "next/image";
import styles from "/src/common/styles/Home.module.css";
import Button from "@mui/material/Button";

export default function Home() {
  const [load, setLoad] = useState(false);

  const handleClick = () => {
    setLoad(true);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Product Administer App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{ color: "black" }}>
          Welcome to <br />
          Product Administer App
        </h1>
        <Link href="/admin">
          <Button variant="contained" onClick={handleClick}>
            {load ? "Loading...." : "Admin Page"}
          </Button>
        </Link>
      </main>

      <footer className={styles.footer}>
        <p>oki@2022</p>
      </footer>
    </div>
  );
}
